# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.111.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    delete_derived_data

    swiftlint(
      mode: :lint, # SwiftLint mode: :lint (default) or :autocorrect
      output_file: "swiftlint/result.json",
      config_file: ".swiftlint.yml",
      strict: true, # Fail on warnings? (true/false)
      ignore_exit_status: false # Allow fastlane to continue even if SwiftLint returns a non-zero exit status
    )

    scan(
      scheme: "NDK",
      devices: ["iPhone 7"],
      clean: true,
      code_coverage: true
    )

    slather(
      output_directory: "slather/coverage",
      scheme: "NDK",
      proj: "NDK.xcodeproj",
      html: true,
      ignore: [
        "NDK/Source/Extensions/UICollectionView.swift",
        "NDK/Source/Extensions/UICollectionViewLayout.swift",
        "NDK/Source/Extensions/UIStoryboard.swift",
        "NDK/Source/Extensions/UITableView.swift",
        "NDK/Source/Utils/NDK.swift",
        "NDK/Source/Utils/StoryboardIdentifiable.swift"
      ]
    )
  end

  desc "Deletes Xcode's derived data"
  lane :delete_derived_data do
    clear_derived_data
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
